baseURL = "https://eh-jogos.github.io/eh_DocsExporter/"
languageCode = "en-us"
title = "eh_jogos Godot Docs Exporter"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# hugo-theme-learn prameters
[params]
	themeVariant = "eh-docs-exporter"
	#themeVariant = "green"
	disableShortcutsTitle = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

